################################################################
# Affiliated packages                                          #
################################################################

# astropy-helpers has a recipe template
- name: astropy-helpers
  version: 1.3

- name: astroquery
  # Version should match the version on PyPI. Versions that could be
  # interpereted as numbers (e.g. 0.1) should be enclosed in quotes.
  version: 0.3.4

  # conda builds disable downloading, but astropy-helpers is typically
  # configured to try to autoupdate during install of affiliated
  # packages. Set to true if the package uses astropy-helpers and
  # auto-update and the --offline flag will be passed to setup.py.
  setup_options: '--offline'   # Defaults to false if omitted.

  # If the package contains compiled extensions that link to numpy this
  # must be set to true to ensure the package is built properly.
  # If in doubt, set it to true...though it should *always* be false
  # for a pure python package.
  numpy_compiled_extensions: false   # Defaults to false if omitted.

  # Some packages can only be built for specific versions of python but
  # setup.py often does not contain those restrictions (and conda skeleton
  # ignores it if present), so list restrictions on python version here.

  # python: '>2.6|>=3.4'  # if omitted, no restriction on python builds.

- name: gammapy
  version: '0.5'
  setup_options: '--offline'
  numpy_compiled_extensions: false
  python: '<3.5.2'
  include_extras: false
